#cloud-config
#
## Add users to the system. Users are added after groups are added.
users:
  - name: provisioner
    groups: sudo, docker
    # this user, ALL hosts=(runas ALL) nopasswd: ALL commands
    # demo ALL=(ALL) NOPASSWD:ALL
    sudo: ['ALL=(ALL) NOPASSWD:ALL']
    lock_passwd: false #enables password login
    passwd: $6$0OJY3T54Cv9j$AjwRVd0ajTBrrNLPDoI.4BddnYmDMewJG2ArqpLls3VgAqLSI2RiOd5pL8P2yn8h5RQhcqyuBgjRDXTV9EuQY/

# does this need to be in a separate meta-data file?
datasource:
  NoCloud:
    meta-data:
      instance-id: 12345678
      local-hostname: provisioner
